In [1]:
class FourCal:
    def __init__(self,a,b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
aCal = FourCal(4,2)
bCal = FourCal(3,8)
print(aCal.add())
print(bCal.add())

6
11


In [2]:
class FourCal:
    def __init__(self,a,b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
    def div(self):
        result = self.first/self.second
        return result
class MoreFourCal(FourCal):
    def pow(self):
        result = self.first**self.second
        return result
    def div(self):
        if self.second == 0:
            self.second = 0.00000000001
        result = self.first/self.second
        return result
    
c = MoreFourCal(4,0)
d = c.div()
print(d)

400000000000.0


In [42]:
PI = 3.14

def add_mod2(a, b):
    return  a+b

class Math_mod2:
    def solve(self, r):
        return PI * (r**2)

In [5]:
def positive(x):
    return x > 0
data = [1,-3,2,0,-5,6]
f= filter(positive, data)
print(list(f))

[1, 2, 6]


In [6]:
data=[1,-3,2,0,-5,6]
list(filter(lambda x: x>0, data))

[1, 2, 6]

In [9]:
a= int(input("숫자를 입력하세요"))
a= a+ 1
print(a)

숫자를 입력하세요12
13


In [16]:
a,b= input("숫자 두개를 입력하세요").split()
a = int(a)
b= int(b)
print(a+1,"그리고",b+1)

숫자 두개를 입력하세요11 20
12 그리고 21


In [18]:
a,b,c,d,e= map(int, input("숫자 두개를 입력하세요").split())
print(a+1,b+1,c+1,d+1,e+1)

숫자 두개를 입력하세요2 3 55 61 2
3 4 56 62 3


In [23]:
data1=[1,2,3,5]
data2=[4,5,6,7]
list(zip(data1,data2))

[(1, 4), (2, 5), (3, 6), (5, 7)]

In [24]:
data1=[1,2,3]
data2=[4,5,6]
data3=[7,8,9]
list(zip(data1,data2,data3))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [25]:
data1=["ban","to",3]
data2=[4,5,6]
data3=[7,8,9]
list(zip(data1,data2,data3))

[('ban', 4, 7), ('to', 5, 8), (3, 6, 9)]

In [41]:
data1=["ban","to",3]
data2=[4,5,6]
data3=[7,8,9]
list(zip(data1,data2,data3))

[('ban', 4, 7), ('to', 5, 8), (3, 6, 9)]

In [29]:
import os
os.environ['PATH']

'C:\\Users\\CPB06GameN\\anaconda3;C:\\Users\\CPB06GameN\\anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\CPB06GameN\\anaconda3\\Library\\usr\\bin;C:\\Users\\CPB06GameN\\anaconda3\\Library\\bin;C:\\Users\\CPB06GameN\\anaconda3\\Scripts;C:\\Users\\CPB06GameN\\anaconda3\\bin;C:\\Users\\CPB06GameN\\anaconda3\\condabin;C:\\Users\\CPB06GameN\\anaconda3;C:\\Users\\CPB06GameN\\anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\CPB06GameN\\anaconda3\\Library\\usr\\bin;C:\\Users\\CPB06GameN\\anaconda3\\Library\\bin;C:\\Users\\CPB06GameN\\anaconda3\\Scripts;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Ma

In [30]:
os.getcwd()

'C:\\Users\\CPB06GameN\\내 주피터노트북'

In [34]:
import glob
glob.glob('C:\\Users\\CPB06GameN\\내 주피터노트북\\*.*') # 안에 있는 파일 위치 전부 알아보기
glob.glob('C:\\Users\\CPB06GameN\\내 주피터노트북\\*.py') # 안에 있는 py  전부 알아보기

['C:\\Users\\CPB06GameN\\내 주피터노트북\\mod1.py',
 'C:\\Users\\CPB06GameN\\내 주피터노트북\\mod2.py']

In [56]:
import mod3

In [58]:
from mod3 import add_col

In [59]:
add_col(2,3)

5

In [50]:
import time
time.time()

1622012858.888627

In [52]:
time.localtime(time.time())

time.struct_time(tm_year=2021, tm_mon=5, tm_mday=26, tm_hour=16, tm_min=8, tm_sec=42, tm_wday=2, tm_yday=146, tm_isdst=0)

In [62]:
for i in range(10):
    print(i)
    time.sleep(0.5) #time.sleep은 원하는 시간대를 입력하면 입력한 시간초씩 숫자를 요청한다.

0
1
2
3
4
5
6
7
8
9


In [63]:
import random
random.random()

0.9299483675280044

In [64]:
random.randint(1,10)

2

In [75]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for i in range(10): my_arr2=my_arr*2 # nparrange 걸리는 시간 12ms

Wall time: 12 ms


In [76]:
%time for i in range(10): my_list2=[x *2 for x in my_list] #list(range()) 걸리는 시간 668ms

Wall time: 668 ms


In [78]:
668/12

55.666666666666664

np함수를 사용하면 실행속도를 더 단축할 수 있다

In [80]:
data = np.random.randn(2,3)
data

array([[ 0.24688335,  1.30823968, -1.58207071],
       [ 1.44033151,  0.53177629, -1.93680501]])

In [81]:
data*10

array([[  2.46883349,  13.08239682, -15.82070705],
       [ 14.40331509,   5.31776286, -19.36805011]])

In [82]:
data+data

array([[ 0.4937667 ,  2.61647936, -3.16414141],
       [ 2.88066302,  1.06355257, -3.87361002]])

In [83]:
data.shape #행렬의 구조 파악 2행 3열의 데이터 모양이다.

(2, 3)

In [84]:
data.dtype # 데이터의 타입을 알려줌, 실수형, 정수형, 문자형

dtype('float64')

In [85]:
data = [6,7.5,8,0,1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [93]:
data2d = [[1,2,3,4],[5,6,7,8]]
arr2d=np.array(data2d)

In [94]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
arr2d.ndim

2

In [96]:
arr2d.shape

(2, 4)

In [97]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
np.zeros((3,6)) #3행 6열

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [99]:
np.zeros((3,6)).shape

(3, 6)

In [104]:
np.zeros((3,3,2)) # 층, 행, 열

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [105]:
np.zeros((3,3,2)).shape

(3, 3, 2)

In [106]:
np.zeros((3,3,2)).dtype # 소수점

dtype('float64')

GPU는 기본적으로 실수형으로 되어있다. CPU는 정수형으로 되어있다.

In [109]:
arr= np.zeros((2,3,2), dtype=np.int32) #타입을 바꿀때는 이렇게 선언해주면 바뀐다. 

In [111]:
arr.dtype

dtype('int32')

In [112]:
arr1=np.zeros((2,3))
arr2=np.ones_like(arr1)
arr2.shape
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
arr3 = np.full((2,3),5) #2행 3열을 5로 채워라

In [114]:
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [115]:
arr4 = np.eye(2) # 2행 2열의 1,0,0,1
arr4

array([[1., 0.],
       [0., 1.]])