In [4]:
#!pip install torch cuda

In [5]:
import torch
import numpy as np

In [6]:
torch.__version__

'1.9.0+cpu'

In [7]:
data = [[1,2],[3,4]]

In [8]:
np_data = np.array(data)

In [9]:
np_data

array([[1, 2],
       [3, 4]])

In [10]:
x_data = torch.tensor(data)

In [11]:
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
x_data_f = torch.FloatTensor(data)
x_data_f

tensor([[1., 2.],
        [3., 4.]])

In [13]:
x_data_f.dim()

2

In [14]:
x_data_f.shape

torch.Size([2, 2])

In [15]:
x_data_f.size()

torch.Size([2, 2])

In [16]:
x_data_f[0]

tensor([1., 2.])

In [17]:
x_data_f[0][1]

tensor(2.)

In [18]:
x_data_f[0][:]

tensor([1., 2.])

In [19]:
t1 = torch.FloatTensor([[3,3]])
t2 = torch.FloatTensor([[2,4]])
print(t1 + t2)

tensor([[5., 7.]])


In [20]:
x_data_f.mean()

tensor(2.5000)

In [21]:
x_data_f.mean(dim=0)

tensor([2., 3.])

In [22]:
x_data_f.mean(dim=1)

tensor([1.5000, 3.5000])

In [23]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2,4]])

In [24]:
torch.cat([t1,t2], dim=0)

tensor([[1., 3.],
        [2., 4.]])

In [25]:
torch.cat([t1,t2], dim=1)

tensor([[1., 3., 2., 4.]])

In [26]:
t3 = torch.FloatTensor([[5,6]])
t4 = torch.stack([t1,t2,t3])
t4

tensor([[[1., 3.]],

        [[2., 4.]],

        [[5., 6.]]])

In [27]:
torch.ones_like(t4)

tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

In [28]:
torch.zeros_like(t4)

tensor([[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]])

In [29]:
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

## 가설 설정
- y=W*x+b (b = bias)
- 기존 머신러닝: MSE평균제곱오차

## 딥러닝 세상의 인식 체계
- cost function(비용함수)=loss function(손실함수)
- = error function(오차 함수) = objective function(목적함수)
- 옵티마이저는 경사하강법(Gradient Descent)을 사용 (Ex. 머신러닝에서 fit)

In [30]:
print(X_train)
print(X_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [31]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [32]:
# 함수 초기화 시키는 작업
W = torch.zeros(1, requires_grad=True)

In [33]:
print(W)

tensor([0.], requires_grad=True)


In [34]:
b = torch.zeros(1,requires_grad = True)
print(b)

tensor([0.], requires_grad=True)


## 현재의 상태
- y = 0*x+0

In [35]:
# 수식 설정 y = (X_train)*W + b
hypothesis = X_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [36]:
#평균 제곱 오차
cost = torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [37]:
import torch.optim as optim
optimizer = optim.SGD([W, b], lr=0.01)

In [38]:
optimizer.zero_grad()
cost.backward()

In [39]:
optimizer.step()

In [51]:
import matplotlib.pyplot as plt
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 썼던 수식들 초기화 함수들 W,b
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1,requires_grad = True)

optimizer = optim.SGD([W, b], lr=0.001) #lr learning rate

nb_epochs = 20000   #실행을 충분히 하기위해 많이 돌려봄
list_cost = []
for epoch in range(nb_epochs):
    hypothesis = X_train*W+b 
    cost = torch.mean((hypothesis-y_train)**2)
  
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 200 == 0:
        list_cost.append(cost.item())
        print('Epoch{:4d}/{} W:{:.3f}, b:{:.3f} cost:{:.5f}'.format(epoch,nb_epochs,W.item(),b.item(),cost.item()))

#print(list_cost)
#plt.plot(range(100),list_cost,marker='x') 커널 나가서 그림으로 안그림


Epoch   0/20000 W:0.019, b:0.008 cost:18.66667
Epoch 200/20000 W:1.513, b:0.624 cost:0.28531
Epoch 400/20000 W:1.686, b:0.661 cost:0.06679
Epoch 600/20000 W:1.717, b:0.637 cost:0.05845
Epoch 800/20000 W:1.732, b:0.608 cost:0.05306
Epoch1000/20000 W:1.745, b:0.579 cost:0.04820
Epoch1200/20000 W:1.757, b:0.552 cost:0.04378
Epoch1400/20000 W:1.768, b:0.526 cost:0.03976
Epoch1600/20000 W:1.779, b:0.502 cost:0.03612
Epoch1800/20000 W:1.790, b:0.478 cost:0.03281
Epoch2000/20000 W:1.800, b:0.456 cost:0.02980
Epoch2200/20000 W:1.809, b:0.434 cost:0.02707
Epoch2400/20000 W:1.818, b:0.414 cost:0.02458
Epoch2600/20000 W:1.826, b:0.394 cost:0.02233
Epoch2800/20000 W:1.835, b:0.376 cost:0.02028
Epoch3000/20000 W:1.842, b:0.358 cost:0.01842
Epoch3200/20000 W:1.850, b:0.341 cost:0.01673
Epoch3400/20000 W:1.857, b:0.325 cost:0.01520
Epoch3600/20000 W:1.864, b:0.310 cost:0.01381
Epoch3800/20000 W:1.870, b:0.296 cost:0.01254
Epoch4000/20000 W:1.876, b:0.282 cost:0.01139
Epoch4200/20000 W:1.882, b:0.268 

## 가설 설정 : x가 3개인 다변량 회귀
- y =W1*x1 +W2*x2 +W3*x3 +b

In [62]:
X1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
X2_train = torch.FloatTensor([[80],[88],[91],[98],[66]])
X3_train = torch.FloatTensor([[75],[93],[90],[100],[70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

W1 = torch.zeros(1, requires_grad=True)
W2 = torch.zeros(1, requires_grad=True)
W3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1,requires_grad = True)

optimizer = optim.SGD([W1,W2,W3, b], lr= 0.000001)
nb_epochs=600000
for epoch in range(nb_epochs):
    hypothesis = (X1_train*W1)+(X2_train*W2)+(X3_train*W3)+b 
    cost = torch.mean((hypothesis-y_train)**2)
  
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 20000 == 0:
        list_cost.append(cost.item())
        print('Epoch{:4d}/{} W1:{:.3f},W2:{:.3f},W3:{:.3f}, b:{:.3f} cost:{:.5f}'.format(epoch,nb_epochs,W1.item(),W2.item(),W3.item(),b.item(),cost.item()))

Epoch   0/600000 W1:0.029,W2:0.029,W3:0.030, b:0.000 cost:29661.80078
Epoch20000/600000 W1:0.757,W2:0.571,W3:0.682, b:0.011 cost:0.75468
Epoch40000/600000 W1:0.812,W2:0.517,W3:0.681, b:0.013 cost:0.44871
Epoch60000/600000 W1:0.848,W2:0.488,W3:0.675, b:0.015 cost:0.33744
Epoch80000/600000 W1:0.871,W2:0.472,W3:0.667, b:0.018 cost:0.29273
Epoch100000/600000 W1:0.888,W2:0.464,W3:0.658, b:0.020 cost:0.27120
Epoch120000/600000 W1:0.901,W2:0.461,W3:0.649, b:0.021 cost:0.25803
Epoch140000/600000 W1:0.911,W2:0.461,W3:0.639, b:0.023 cost:0.24828
Epoch160000/600000 W1:0.919,W2:0.462,W3:0.630, b:0.025 cost:0.24010
Epoch180000/600000 W1:0.927,W2:0.464,W3:0.621, b:0.027 cost:0.23309
Epoch200000/600000 W1:0.933,W2:0.466,W3:0.612, b:0.028 cost:0.22697
Epoch220000/600000 W1:0.939,W2:0.468,W3:0.604, b:0.030 cost:0.22126
Epoch240000/600000 W1:0.945,W2:0.471,W3:0.596, b:0.032 cost:0.21588
Epoch260000/600000 W1:0.950,W2:0.473,W3:0.588, b:0.033 cost:0.21143
Epoch280000/600000 W1:0.955,W2:0.476,W3:0.581, b:0

## 결론 :learning rate와 epoch 값을 유동적으로 넣어가며 최적의(0에 수렴하는) cost값을 찾아내야함

In [63]:
import torch.nn as nn

In [68]:
model = nn.Linear(1,1) #(input_dim=1,output_dim=1)

In [70]:
print(list(model.parameters())) # [Parameter containing:
#                                 tensor([[W값]], requires_grad=True), Parameter containing:
#                                 tensor([b값], requires_grad=True)]

[Parameter containing:
tensor([[0.6123]], requires_grad=True), Parameter containing:
tensor([-0.9747], requires_grad=True)]


In [98]:
import torch.nn as nn
import torch.nn.functional as F
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
model =nn.Linear(1,1)

optimizer = optim.SGD(model.parameters(), lr = 0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(X_train)
    cost = F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch{:4d}/{} loss:{:.5f}'.format(epoch,nb_epochs,cost.item()))

Epoch   0/2000 loss:4.74249
Epoch 100/2000 loss:0.01607
Epoch 200/2000 loss:0.00993
Epoch 300/2000 loss:0.00614
Epoch 400/2000 loss:0.00379
Epoch 500/2000 loss:0.00234
Epoch 600/2000 loss:0.00145
Epoch 700/2000 loss:0.00089
Epoch 800/2000 loss:0.00055
Epoch 900/2000 loss:0.00034
Epoch1000/2000 loss:0.00021
Epoch1100/2000 loss:0.00013
Epoch1200/2000 loss:0.00008
Epoch1300/2000 loss:0.00005
Epoch1400/2000 loss:0.00003
Epoch1500/2000 loss:0.00002
Epoch1600/2000 loss:0.00001
Epoch1700/2000 loss:0.00001
Epoch1800/2000 loss:0.00000
Epoch1900/2000 loss:0.00000
Epoch2000/2000 loss:0.00000


## 계속 시행값이 달라지는 이유
- optimizer 함수가 값을 산출할 때 w값에 대한 계산을 랜덤으로 가져간다. 
- 그래서 똑같은 learning mate 값과 epoch를 넣고 돌릴때 계속 달라지는 이유이다. 
- 그래서 y_pred 값이 산출 될 때 계속 조금씩 값이 틀려지는 이유이다.
- 이것은 잘못된 것이 아니다.

## 내가 제시한 방향성
- 값들을 계속 돌려보면서 나오는 값들의 평균값을 알려준다.

## 강사님의 말씀
- 더욱 정확한 값을 원하면 x_train, y_train 값을 정밀하게 가져가서 값을 찾는다

In [99]:
# 새로운 데이터를 FloatTensor에 넣고 예측값을 산출해본다.
new_input = torch.FloatTensor([[1.5]])
pred_y = model(new_input)
pred_y

tensor([[3.0012]], grad_fn=<AddmmBackward>)