In [1]:
from sklearn.datasets import load_files

In [2]:
review_train = load_files('aclImdb/train/')

In [3]:
text_train, y_train = review_train.data, review_train.target

In [4]:
y_train[1]

0

In [5]:
text_train[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [6]:
len(text_train)

25000

In [7]:
text_train = [a_review.replace(b"<br />",b" ")for a_review in text_train]

In [8]:
text_train[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.  It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see.   Flawed but honest with a terrible honesty."

In [9]:
import numpy as np
np.bincount(y_train)

array([12500, 12500], dtype=int64)

In [10]:
reviews_test = load_files('aclImdb/test/')
text_test,y_test = reviews_test.data,reviews_test.target

In [11]:
len(text_test)

25000

In [12]:
np.bincount(y_test)

array([12500, 12500], dtype=int64)

In [29]:
text_test = [a_review.replace(b"<br />",b" ")for a_review in text_test]

In [30]:
bards_words = ["The fool doth think he is wise,",
              "but the wise man knows himself to be a fool"]

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(bards_words)

CountVectorizer()

In [32]:
len(vect.vocabulary_)

13

In [33]:
vect.vocabulary_

{'the': 9,
 'fool': 3,
 'doth': 2,
 'think': 10,
 'he': 4,
 'is': 6,
 'wise': 12,
 'but': 1,
 'man': 8,
 'knows': 7,
 'himself': 5,
 'to': 11,
 'be': 0}

In [34]:
bag_of_words = vect.transform(bards_words)
bag_of_words.toarray()

array([[0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1]], dtype=int64)

In [35]:
vect = CountVectorizer().fit(text_train)
X_train = vect.transform(text_train)
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
feature_names = vect.get_feature_names()

In [37]:
len(feature_names)

74849

In [38]:
feature_names[:10]

['00',
 '000',
 '0000000000001',
 '00001',
 '00015',
 '000s',
 '001',
 '003830',
 '006',
 '007']

In [39]:
feature_names[20000:20010]

['draper',
 'draperies',
 'drapery',
 'drapes',
 'draskovic',
 'drastic',
 'drastically',
 'drat',
 'dratch',
 'dratic']

In [40]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

scores = cross_val_score(LogisticRegression(max_iter=1000),
                        X_train,y_train,cv=5)
scores

array([0.8824, 0.876 , 0.882 , 0.8884, 0.8776])

In [41]:
X_test = vect.transform(text_test)

In [42]:
lr = LogisticRegression(max_iter=1000).fit(X_train,y_train)
y_pred = lr.predict(X_test[10000]) #X_test값에 원하는 인덱스 넣어서 예측해줌

In [43]:
y_pred[0],y_test[10000] # 예측값으로 긍정이 산출됨

(0, 0)

In [44]:
text_test[10000]

b"An expedition led by hunky Captain Storm (Mark Dana) travels to the Valley of the Kings in Cairo to find out what happened to an earlier expedition. They meet beautiful mysterious Simira (Ziva Rodann) who joins them. They soon find themselves faced with a blood drinking mummy...and only Simira seems to know what's going on.  A real snoozer. I caught this on late night TV when I was about 10. It put me to sleep! Seeing it again all these years later I can see why. It's slow-moving, the mummy doesn't even show up until 40 minutes in (and this is only 66 minutes long!), the acting ranges from bad (Dana) to REAL bad (George N. Neise) and there's no violence or blood to be found. This movie concentrates more on second rate dramatics (involving a silly love triangle) than horror.  This rates three stars because it actually looks pretty good, everyone plays it straight, there's some good acting from Diane Brewster, it's short and the mummy attack scenes (all three of them) aren't bad. They'